version: '3.7'
services:
  db:
    image: postgres:12
    env_file:
      - docker-compose-env/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: gunicorn library.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - docker-compose-env/web.env
volumes:
  postgres_data:
