version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
     - 6379:6379
  db:
    image: postgres:12
    env_file:
      - docker-compose-env/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    image: celery
    command: celery -A library worker --pool=solo -l info
    volumes:
      - .:/code
    links:
      - redis
  web:
    build: .
    command: gunicorn library.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery
    env_file:
      - docker-compose-env/web.env
volumes:
  postgres_data: