# Generated by Django 3.0.6 on 2020-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200531_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
