# Generated by Django 3.0.6 on 2020-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
