# Generated by Django 3.0.8 on 2020-07-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 15, 25, 38, 951228)),
        ),
        migrations.AddField(
            model_name='book',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 15, 25, 38, 951251)),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
